In [1]:
import osmium as osm
import pandas as pd

In [3]:
import osmium as osm
import pandas as pd

class OSMHandler(osm.SimpleHandler):
    def __init__(self):
        osm.SimpleHandler.__init__(self)
        self.osm_data = []

    def tag_inventory(self, elem, elem_type):
        for tag in elem.tags:
            self.osm_data.append([elem_type, 
                                   elem.id, 
                                   elem.version,
                                   elem.visible,
                                   pd.Timestamp(elem.timestamp),
                                   elem.uid,
                                   elem.user,
                                   elem.changeset,
                                   len(elem.tags),
                                   tag.k, 
                                   tag.v])

    def node(self, n):
        self.tag_inventory(n, "node")

    def way(self, w):
        self.tag_inventory(w, "way")

    def relation(self, r):
        self.tag_inventory(r, "relation")


osmhandler = OSMHandler()
# scan the input file and fills the handler list accordingly
osmhandler.apply_file("map.osm")

# transform the list into a pandas DataFrame
data_colnames = ['type', 'id', 'version', 'visible', 'ts', 'uid',
                 'user', 'chgset', 'ntags', 'tagkey', 'tagvalue']
df_osm = pd.DataFrame(osmhandler.osm_data, columns=data_colnames)
df_osm = df_osm.sort_values(by=['type', 'id', 'ts'])

In [4]:
df_osm

,type,id,version,visible,ts,uid,user,chgset,ntags,tagkey,tagvalue
0,node,10980707,15,True,2021-06-15 15:45:35+00:00,1676637,Kilkenni,106411428,5,button_operated,no
1,node,10980707,15,True,2021-06-15 15:45:35+00:00,1676637,Kilkenni,106411428,5,crossing,traffic_signals
2,node,10980707,15,True,2021-06-15 15:45:35+00:00,1676637,Kilkenni,106411428,5,highway,traffic_signals
3,node,10980707,15,True,2021-06-15 15:45:35+00:00,1676637,Kilkenni,106411428,5,traffic_signals:sound,no
4,node,10980707,15,True,2021-06-15 15:45:35+00:00,1676637,Kilkenni,106411428,5,traffic_signals:vibration,no
...,...,...,...,...,...,...,...,...,...,...,...
31164,way,1237869831,1,True,2024-01-07 20:15:55+00:00,18547530,Валентин Ян,146004875,3,lit,yes
31165,way,1237869831,1,True,2024-01-07 20:15:55+00:00,18547530,Валентин Ян,146004875,3,surface,paving_stones
31166,way,1239067289,1,True,2024-01-12 10:19:24+00:00,18547530,Валентин Ян,146175141,1,natural,tree_row
31167,way,1239067290,1,True,2024-01-12 10:19:24+00:00,18547530,Валентин Ян,146175141,1,highway,footway
31168,way,1239067291,1,True,2024-01-12 10:19:24+00:00,18547530,Валентин Ян,146175141,1,highway,service

In [5]:
df_osm['tagkey'].value_counts()

tagkey
highway      4529
name         1991
name:uk      1877
surface      1224
building     1046
             ...
name:la         1
name:no         1
consulate       1
name:sk         1
dog             1
Name: count, Length: 575, dtype: int64

In [6]:
df_osm['type'].value_counts()

type
node        16799
way         14370
relation     2330
Name: count, dtype: int64